apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  name: nginx
spec:
  rules:
    - host: space.k8s.hackability.dev
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: hackability
                port:
                  number: 3000
  tls:
    - hosts:
        - space.k8s.hackability.dev
      secretName: space.k8s.hackability.dev-tls
