name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Timestamp
        id: get_timestamp
        run: |
          TS=$(date +%s)
          echo "::set-output name=timestamp::$TS"
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/${{ github.repository }}/app
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
          tag-custom: |
            ts-${{ steps.get_timestamp.outputs.timestamp }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     labels: ${{ steps.docker_meta.outputs.labels }}
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
